# P1 — Cedar Dental: Appointment Register Cleanup
**Scenario:** Cedar Dental has exported 515 appointment records. The data has missing values,
duplicate rows, and inconsistent appointment type labels. This notebook cleans the dataset
and produces a client-ready output file.

**Input:** `appointments_raw.csv`  
**Output:** `appointments_cleaned_YYYYMMDD.csv`  
**Libraries:** pandas only

In [2]:
import pandas as pd
from datetime import datetime #  imports the datetime class from Python's built-in datetime module

df = pd.read_csv(r"C:\Users\clemo\Downloads\appointments_raw.csv")
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,15/10/2024,Filling,Dr. Patel,no
1,APT0002,P0053,20/09/2024,Chekup,NaN,0
2,APT0003,NaN,05/02/2024,extraction,Dr. Patel,Yes
3,APT0004,P0367,09/09/2024,Clean,Dr. Patel,NaN
4,APT0005,P0004,22/10/2024,Extraction,Dr. Williams,1
...,...,...,...,...,...,...
510,APT0323,P0045,26/01/2024,filling,Dr. Williams,NaN
511,APT0169,P0123,10/08/2024,cleaning,Dr. Patel,0
512,APT0120,P0375,18/08/2024,Filling,Dr. Nguyen,no
513,APT0067,P0342,09/02/2024,Cleaning,NaN,0
514,APT0306,P0165,09/02/2024,Chekup,Dr. Nguyen,YES

## 1. Data Inspection

In [3]:
# Finding the shape of the dataframe
print("Shape:", df.shape)

Shape: (515, 6)

In [4]:
# Finding the datatypes of each set of data in the columns
print("Column types:")
print(df.dtypes)

Column types:
appointment_id      object
patient_id          object
appointment_date    object
appointment_type    object
therapist           object
attended            object
dtype: object

In [5]:
# Finds the null values in each data set
print("Null counts:")
print(df.isnull().sum())

Null counts:
appointment_id        0
patient_id           20
appointment_date      0
appointment_type      0
therapist           102
attended             76
dtype: int64

In [6]:
# Finds the sum of the duplicated values in each row
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 15

## 2. Fix: Drop duplicate Rows

In [7]:
## Finds all the duplicate values
df[df.duplicated()]

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
500,APT0305,P0373,14/06/2024,Chekup,Dr. Williams,yes
501,APT0341,P0082,12/11/2024,Fillig,NaN,1
502,APT0048,P0245,14/07/2024,Consult,Dr. Patel,Yes
503,APT0068,P0384,01/03/2024,EXTRACTION,Dr. Patel,yes
504,APT0480,P0248,10/02/2024,filling,Dr. Williams,No
505,APT0486,P0170,05/08/2024,Clean,Dr. Williams,no
506,APT0311,P0399,08/09/2024,Cleaning,Dr. Nguyen,0
507,APT0032,P0333,25/05/2024,Consultation,NaN,NaN
508,APT0250,P0055,04/04/2024,Clean,NaN,0
509,APT0091,P0357,20/07/2024,Consultation,Dr. Ahmed,no
510,APT0323,P0045,26/01/2024,filling,Dr. Williams,NaN
511,APT0169,P0123,10/08/2024,cleaning,Dr. Patel,0
512,APT0120,P0375,18/08/2024,Filling,Dr. Nguyen,no
513,APT0067,P0342,09/02/2024,Cleaning,NaN,0
514,APT0306,P0165,09/02/2024,Chekup,Dr. Nguyen,YES

In [8]:
## Drops/Removes all the duplicate values
df = df.drop_duplicates().copy()

In [9]:
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,15/10/2024,Filling,Dr. Patel,no
1,APT0002,P0053,20/09/2024,Chekup,NaN,0
2,APT0003,NaN,05/02/2024,extraction,Dr. Patel,Yes
3,APT0004,P0367,09/09/2024,Clean,Dr. Patel,NaN
4,APT0005,P0004,22/10/2024,Extraction,Dr. Williams,1
...,...,...,...,...,...,...
495,APT0496,P0295,29/05/2024,Clean,Dr. Patel,NaN
496,APT0497,P0356,24/12/2024,Extraction,NaN,yes
497,APT0498,P0072,13/03/2024,Fillig,Dr. Williams,Yes
498,APT0499,P0005,07/07/2024,Check Up,Dr. Patel,0
499,APT0500,P0259,11/09/2024,consultation,Dr. Williams,NaN

In [10]:
## Now we have removed all duplicate values from our dataframe
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0

## 3. Fix appointment_type - Standardise Labels

In [11]:
# Step 1: normalise casing and whitespace first
df['appointment_type'] = df['appointment_type'].str.lower().str.strip()
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,15/10/2024,filling,Dr. Patel,no
1,APT0002,P0053,20/09/2024,chekup,NaN,0
2,APT0003,NaN,05/02/2024,extraction,Dr. Patel,Yes
3,APT0004,P0367,09/09/2024,clean,Dr. Patel,NaN
4,APT0005,P0004,22/10/2024,extraction,Dr. Williams,1
...,...,...,...,...,...,...
495,APT0496,P0295,29/05/2024,clean,Dr. Patel,NaN
496,APT0497,P0356,24/12/2024,extraction,NaN,yes
497,APT0498,P0072,13/03/2024,fillig,Dr. Williams,Yes
498,APT0499,P0005,07/07/2024,check up,Dr. Patel,0
499,APT0500,P0259,11/09/2024,consultation,Dr. Williams,NaN

In [12]:
# Step 2: check what you're working with after normalisation
print(df['appointment_type'].value_counts())

appointment_type
extraction      75
filling         69
consultation    69
cleaning        54
fillig          39
check-up        37
check up        35
chekup          34
clean           33
consult         30
checkup         25
Name: count, dtype: int64

In [13]:
 # Step 3: map dirty variants to 5 clean labels
correct_map = {
    'filling':  'filling',
    'fillig':        'filling',    # typo
    'check-up':      'check-up',
    'checkup':       'check-up',
    'check up':      'check-up',
    'chekup':        'check-up',   # typo
    'cleaning':      'cleaning',
    'clean':         'cleaning',
    'extraction':    'extraction',
    'consultation':  'consultation',
    'consult':       'consultation'
}

df['appointment_type'] = df['appointment_type'].map(correct_map)
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,15/10/2024,filling,Dr. Patel,no
1,APT0002,P0053,20/09/2024,check-up,NaN,0
2,APT0003,NaN,05/02/2024,extraction,Dr. Patel,Yes
3,APT0004,P0367,09/09/2024,cleaning,Dr. Patel,NaN
4,APT0005,P0004,22/10/2024,extraction,Dr. Williams,1
...,...,...,...,...,...,...
495,APT0496,P0295,29/05/2024,cleaning,Dr. Patel,NaN
496,APT0497,P0356,24/12/2024,extraction,NaN,yes
497,APT0498,P0072,13/03/2024,filling,Dr. Williams,Yes
498,APT0499,P0005,07/07/2024,check-up,Dr. Patel,0
499,APT0500,P0259,11/09/2024,consultation,Dr. Williams,NaN

In [14]:
# Step 4: verify — should be 0 nulls and exactly 5 unique values
print(df['appointment_type'].value_counts()) 
print("Unmapped (nulls introduced):", df['appointment_type'].isnull().sum())

appointment_type
check-up        131
filling         108
consultation     99
cleaning         87
extraction       75
Name: count, dtype: int64
Unmapped (nulls introduced): 0

## 4. Fix: appointment_date — Parse to datetime

In [15]:
# Standardise the dates and if you cannot parse a date then turn it into NaT
df['appointment_date'] = pd.to_datetime(df['appointment_date'], dayfirst=True, errors='coerce')
# Check how many bad dates got nulled out
print(df['appointment_date'].isnull().sum())

1

In [16]:
# pd.to_datetime() converts dates into a full datetime object — date and time. Since your data has no time information, it just fills the time part with 00:00:00 as a default.
# If we want clean dates only then:
df['appointment_date'] = df['appointment_date'].dt.date
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,2024-10-15,filling,Dr. Patel,no
1,APT0002,P0053,2024-09-20,check-up,NaN,0
2,APT0003,NaN,2024-02-05,extraction,Dr. Patel,Yes
3,APT0004,P0367,2024-09-09,cleaning,Dr. Patel,NaN
4,APT0005,P0004,2024-10-22,extraction,Dr. Williams,1
...,...,...,...,...,...,...
495,APT0496,P0295,2024-05-29,cleaning,Dr. Patel,NaN
496,APT0497,P0356,2024-12-24,extraction,NaN,yes
497,APT0498,P0072,2024-03-13,filling,Dr. Williams,Yes
498,APT0499,P0005,2024-07-07,check-up,Dr. Patel,0
499,APT0500,P0259,2024-09-11,consultation,Dr. Williams,NaN

In [17]:
# attended column has: yes, YES, Yes, 1, no, No, 0
print(df['attended'].value_counts())

attended
0      68
yes    62
no     61
1      61
Yes    59
YES    58
No     57
Name: count, dtype: int64

In [18]:
bool_map = {
    '0':  False,
    'yes' : True,
    'no': False,
    '1': True,
    'Yes': True,
    'YES': True,
    'No': False}

df['attended'] = df['attended'].map(bool_map)
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended
0,APT0001,P0013,2024-10-15,filling,Dr. Patel,False
1,APT0002,P0053,2024-09-20,check-up,NaN,False
2,APT0003,NaN,2024-02-05,extraction,Dr. Patel,True
3,APT0004,P0367,2024-09-09,cleaning,Dr. Patel,NaN
4,APT0005,P0004,2024-10-22,extraction,Dr. Williams,True
...,...,...,...,...,...,...
495,APT0496,P0295,2024-05-29,cleaning,Dr. Patel,NaN
496,APT0497,P0356,2024-12-24,extraction,NaN,True
497,APT0498,P0072,2024-03-13,filling,Dr. Williams,True
498,APT0499,P0005,2024-07-07,check-up,Dr. Patel,False
499,APT0500,P0259,2024-09-11,consultation,Dr. Williams,NaN

## 5. Fix: patient_id — Flag Missing Records

In [19]:
# Creating a new column called record_status. 'Incomplete' if pateient_id is null, therapist is null and attended is null. 'Complete' everywhere else
df['record_status'] = df.apply(
    lambda row: 'Incomplete' 
    if pd.isnull(row['patient_id']) or pd.isnull(row['therapist']) or pd.isnull(row['attended'])
    else 'Complete', axis=1
)


# To verify this
print(df['record_status'].value_counts())

record_status
Complete      324
Incomplete    176
Name: count, dtype: int64

In [20]:
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended,record_status
0,APT0001,P0013,2024-10-15,filling,Dr. Patel,False,Complete
1,APT0002,P0053,2024-09-20,check-up,NaN,False,Incomplete
2,APT0003,NaN,2024-02-05,extraction,Dr. Patel,True,Incomplete
3,APT0004,P0367,2024-09-09,cleaning,Dr. Patel,NaN,Incomplete
4,APT0005,P0004,2024-10-22,extraction,Dr. Williams,True,Complete
...,...,...,...,...,...,...,...
495,APT0496,P0295,2024-05-29,cleaning,Dr. Patel,NaN,Incomplete
496,APT0497,P0356,2024-12-24,extraction,NaN,True,Incomplete
497,APT0498,P0072,2024-03-13,filling,Dr. Williams,True,Complete
498,APT0499,P0005,2024-07-07,check-up,Dr. Patel,False,Complete
499,APT0500,P0259,2024-09-11,consultation,Dr. Williams,NaN,Incomplete

In [21]:
# attended column has: yes, YES, Yes, 1, no, No, NO, 0
print(df['attended'].value_counts())

attended
True     240
False    186
Name: count, dtype: int64

In [22]:
df

,appointment_id,patient_id,appointment_date,appointment_type,therapist,attended,record_status
0,APT0001,P0013,2024-10-15,filling,Dr. Patel,False,Complete
1,APT0002,P0053,2024-09-20,check-up,NaN,False,Incomplete
2,APT0003,NaN,2024-02-05,extraction,Dr. Patel,True,Incomplete
3,APT0004,P0367,2024-09-09,cleaning,Dr. Patel,NaN,Incomplete
4,APT0005,P0004,2024-10-22,extraction,Dr. Williams,True,Complete
...,...,...,...,...,...,...,...
495,APT0496,P0295,2024-05-29,cleaning,Dr. Patel,NaN,Incomplete
496,APT0497,P0356,2024-12-24,extraction,NaN,True,Incomplete
497,APT0498,P0072,2024-03-13,filling,Dr. Williams,True,Complete
498,APT0499,P0005,2024-07-07,check-up,Dr. Patel,False,Complete
499,APT0500,P0259,2024-09-11,consultation,Dr. Williams,NaN,Incomplete

## 6. Export Cleaned File

In [ ]:
today = datetime.today().strftime('%Y%m%d')
output_path = f'../outputs/appointments_cleaned_{today}.csv'
df.to_csv(output_path, index=False)
print(f"Exported: {output_path}")
print(f"Final shape: {df.shape}")

OSError: Cannot save file into a non-existent directory: '..\outputs'